VERSION_MAJOR=0
VERSION_MINOR=5
VERSION_MICRO=0
#VERSION_BETA=6

ifeq (,$(VERSION_BETA)) # [
VERSION=$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_MICRO)
else # ] [
VERSION=$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_MICRO)-beta-$(VERSION_BETA)
endif # ]
